### ISSUE TITLE
Question: State of PaHM in SCHISM

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [noaa-ocs-modeling/PaHM#22]
@pvelissariou1, I recently noticed strange results in my best track simulations and I was wondering if it could  be related to PaHM implementation in SCHISM. I also remember @mojy3995 had issues trying to use parametric wind at one point. So I tested PaHM standalone on Florence track and I'm not sure if the results look right. I tried commit a2e410ca as well as the latest (0bb9ab7e). I'm not sure which one is equivalent to the one embedded in SCHISM, but in either case I don't see the results I was expecting.

**Comment by pvelissariou1** [comment]
Soroosh,

The issues @mojy3995 faced were due to the way PaHM was reading the CSV
files and have been fixed.
What kind of strange results are you getting?

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by SorooshMani-NOAA** [comment]
I'll go over the details in the meeting tomorrow. I'm just plotting the results; for the older commit I see that the mesh is flipped left to right. For the latest version I don't see the flip, but I still see strange contours. I'm still not sure if it's an issue with holoviews or the results are not valid. In any case I would appreciate it if you tell me how would you visualize the results of PaHM for debugging purposes.

**Comment by pvelissariou1** [comment]
The flip in the mesh has been fixed months ago, I don't remember the
commit. Let's talk about this tomorrow.


Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by SorooshMani-NOAA** [comment]
Yes, I remember that you said you fixed an issue like this, I was just not sure if SCHISM also has that fix or not. I'd also like to know what is the best way to visualize the results for debugging

**Comment by pvelissariou1** [comment]
All fixes have been implemented into SCHISM/PaHM as well.
To visualize the PaHM output, you can run PaHM stand-alone to get the
output NetCDF file. The output
is on an ADCIRC type of Mesh.
You can read the NetCDF file and plot the winds out using your plotting
routines.
I usually do point time series comparisons. As far as I know PaHM results
compare well with observations.

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by SorooshMani-NOAA** [comment]
That's what I'm doing as well (using the nc file and reading the `.x` and `.y` and `.P` to plot). So maybe it's the the issue with plotting using holoviews. Do you know if @mojy3995 ever tested to see if she can get a reasonable result from PaHM-SCHISM?

**Comment by pvelissariou1** [comment]
No, I don't know. I don't think she ever compared the wind fields.

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by SorooshMani-NOAA** [comment]
OK, so maybe we need to go through that practice for my case. When Mojy was trying it, I only looked at my older cases, but never ran a case with the latest PaHM. Maybe that's what I should have done. 

In any case, now I'm running the same simulation but with ERA5 data, I'll compare and we'll discuss tomorrow and see if the issue could be PaHM or other things in my setup.

**Comment by SorooshMani-NOAA** [comment]
@pvelissariou1 , following our discussions I tried to plot the mesh elevation for the same mesh I'm using for PaHM and the elevation contour plots look right. So it's not the plotting itself that is the issue. I thought maybe there's something I'm missing about how to plot the PaHM nc data. As I showed you I'm getting dataset's `.x` and `.y` variables and also get `.tri` array and subtract `1 from it  to make the cell connectivity 0-based. When I plot this mesh, the connectivity looks fine, but if I plot contours using `.P` variable of the dataset, I get that strange plot I showed you earlier. For the dataset you sent me, I get a different result but still it doesn't make sense:

This is the dataset you sent me for Florence
![image](https://user-images.githubusercontent.com/77082694/205134342-87b9b039-0e4a-4034-bbac-c323e1fb9f25.png)
 

And this is the result of me running PaHM  for Florence on WNAT_1km mesh:
![image](https://user-images.githubusercontent.com/77082694/205134530-6a8d17ed-330e-40f5-a564-9618973badc0.png)

And this is the same mesh but contours are for elevations:
![image](https://user-images.githubusercontent.com/77082694/205134923-0f660a28-e58a-47a3-b525-012cb93d1075.png)

**Comment by SorooshMani-NOAA** [comment]
@pvelissariou1, I tried running SCHISM with parametric and with ERA5 wind, this is the difference in some of the station results:


This is what I get with **PaHM** forcing in SCHISM:
![image](https://user-images.githubusercontent.com/77082694/205683474-71baaae0-4d66-45d3-bed1-1ead32667e56.png)
![image](https://user-images.githubusercontent.com/77082694/205685484-c9b9273f-1f54-4475-8679-e8e2dc24ab48.png)![image](https://user-images.githubusercontent.com/77082694/205685226-89f99706-987d-4b00-94c3-c70e466b00a4.png)

-----

And this is with **ERA5** forcing:
![image](https://user-images.githubusercontent.com/77082694/205683246-de2144b5-70cc-42bd-a894-f6de0de715d1.png)
![image](https://user-images.githubusercontent.com/77082694/205685571-2e7d7a21-2f4e-4efc-a7de-770867ec3133.png)![image](https://user-images.githubusercontent.com/77082694/205685268-9bee10c7-069a-4a8d-84ae-96e6c076b2a7.png)

I'm using https://github.com/schism-dev/schism/commit/5282a27 to build SCHISM binaries in my Docker image.

I compared SCHISM input directories for the two run (`036` is parametric and `038` is using ERA5) and of the common SCHISM files among these:
```bash
$ ls *
florence_2018_036:
bctides.in  elev.ic  hgrid.ll  hurricane-track.dat  hurricane-track.dat_adj  Makefile  msource.th  param.nml  run_info.json  source_sink.in  station.in  vgrid.in  viz  vsink.th  vsource.th

florence_2018_038:
bctides.in  elev.ic  hgrid.ll  Makefile  msource.th  param.nml  run_info.json  sflux  source_sink.in  station.in  vgrid.in  viz  vsink.th  vsource.th
```
Only `param.nml` and `bctides.in` are different. `pyschism` doesn't sort `bctides.in` the same way every time; if I manually sort both `bctides.in`, the end results is that even `bctides.in` are the same. The difference in `param.nml` is:
```diff
$ DIFFFILE=param.nml; diff florence_2018_036/$DIFFFILE florence_2018_038/$DIFFFILE
23c23
<     nws = -1
---
>     nws = 2
```

Am I using the right version of SCHISM with the latest PaHM code? Also I don't know how to explain the strange plots attached in https://github.com/noaa-ocs-modeling/PaHM/issues/22#issuecomment-1334196785

@saeed-moghimi-noaa suggested that I also try to plot ADCIRC-PAHM results. Can you please provide the address of your results on Hera for ADCIRC-PAHM?

**Comment by pvelissariou1** [comment]
Soroosh hi,

The timeseries you show for PaHM look correct. Don't forget that as you
move away from the hurricane's path the quality of PaHM's winds
deteriorates.
Also, at this point there is no background wind field blended into the PaHM
generated winds.
Regarding the "strange" behavior when you plot the contours for the wind
fields, remember that the 200m HSOFS you are using does not cover the Gulf
completely.
What PaHM does is to read the ocean mesh and then calculates the wind
fields at each node it finds in the mesh.
Have you tried to plot the mesh/nodes?
Also you might want to compare the PaHM wind fields with observations (wind
speed, wind direction, pressure) to see if there are any discrepancies.
We may talk more about this.

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by pvelissariou1** [comment]
Ok, let's chat after the hands-on meeting today.
I'll find my time series plots that compare the wind fields.

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by SorooshMani-NOAA** [comment]
@pvelissariou1 I plotted the Hurricane Sandy results you gave me and this is how it looks:

At timestep `200` (eqv to 2012-10-23T07:59:59.999999872)
![image](https://user-images.githubusercontent.com/77082694/206025461-8fa84413-38af-4df7-9cc1-9b090398adb8.png)

At timestep `250` (eqv to 2012-10-25T10:00:00.000000000)
![image](https://user-images.githubusercontent.com/77082694/206025812-6490da9a-bae5-476f-b2b6-0ee47f401b37.png)

At timestep `325` (eqv to 2012-10-28T13:00:00.000000000)
![image](https://user-images.githubusercontent.com/77082694/206026086-562d5088-c319-4e81-a6a5-8b52d14f28b6.png)


Max of `uwnd` is `200` in the whole dataset

**Comment by pvelissariou1** [comment]
Soroosh hi,

It seems that there is actually a problem with PaHM after the latest
updates to account for the Southern Hemisphere winds.
I am checking to see what is wrong.
I'll keep you posted.

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by pvelissariou1** [comment]
Soroosh hi,

I fixed the issue. The problem was a format issue when reading CSV files.
Checked with gfortran locally.
I pushed the changes to schism and to PaHM/CoastalApp.
You may want to download the latest schism.

Let me know if you still have problems.
Thank you for catching this.

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by SorooshMani-NOAA** [comment]
@pvelissariou1 I tested your latest changes in PaHM standalone and it seems to be working fine. I'll test SCHISM with your fixes as well and let you know how it goes. Below is the wind speed magnitude plot for Florence generated by latest PaHM

![image](https://user-images.githubusercontent.com/77082694/206208225-4cb9a0ef-8551-41a0-b7c4-501b5697aed7.png)

Thanks a lot for taking care of this!

**Comment by SorooshMani-NOAA** [comment]
SCHISM simulation looks fine as well:

![image](https://user-images.githubusercontent.com/77082694/206305500-fdcfda2d-5e79-4561-86ec-d3cfa11834d1.png)
