### ISSUE TITLE
Setup and run PaHM for `BEST` and `OFCL` tracks of florence

### ISSUE THREAD

**Issue by FariborzDaneshvar-NOAA** [noaa-ocs-modeling/PaHM#27]
PaHM was downloaded and compiled on `NHC_Colab_2` cluster on PW. 
directory: `/home/Fariborz.Daneshvar/PaHM`

The following commands were used for compilation:
- `module load intel/2022.1.2 netcdf cmake`
- `./build.sh --compiler intel --platform pworks`

Then a copy of `./templates/pahm_control-ike.in` was created in the PaHM directory and was named `pahm_control_florence.in`. 

For each scenario, the following lines were updated in the `pahm_control_florence.in`:  `bestTrackFileName`, `meshFileName`, `outFileName`, `begDateTime`, `endDateTime`, and `modelType = 10` 

Finally, the following command was used to run each scenario: 
- `./pahm pahm_control_florence.in`

**Comment by FariborzDaneshvar-NOAA** [comment]
@pvelissariou1 I am using `pahm <control_file_name> command in the pahm directory, as you suggested, but getting `pahm: command not found` error (here is a screenshot)



![Image](https://github.com/noaa-ocs-modeling/PaHM/assets/132295102/5aa1c2f4-067c-46df-9f21-7f5dd10cd32e)

**Comment by pvelissariou1** [comment]
The current directory is not in your path it seems. Run it as: ./pahm
control_file.

On Friday, July 28, 2023, Fariborz Daneshvar ***@***.***>
wrote:
> @pvelissariou1 I am using pahm <control_file_name> command in the pahm
directory, as you suggested, but getting pahm: command not found` error
(here is a screenshot)
>
> <
https://ci3.googleusercontent.com/proxy/iDgpwD7QSHrVj03bVt_vj1hRvNbQBkzmzJFLiMoUjFdJthxK6fHZl5yD7ZOURfmdjknYv1BwL7AzVz8V3TQfTMsJaqBrul_Eqqio5OtzfsdNMc-XBZGEKlGFKpDpmT_LzuhvRa9bw0Q6stusI2dQ7I3Qkf2h4zbZDw=s0-d-e1-ft#https://user-images.githubusercontent.com/132295102/256898354-5aa1c2f4-067c-46df-9f21-7f5dd10cd32e.png
>
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci4.googleusercontent.com/proxy/gNJJbVh5tTfIaAmI4Cg_q_L8JJRQ5jxVPYUhu7cQh2Mm51DQeymcPOHbuyiPBCMGrjl3KgeL0k5OV0cHPl1S0QnHXcL-MV0YTFKFSQSJlwXQjsYF62ABEZ67FoXc4xpDEfnc2pzdDuAs9s6oliEYjSKdP-SFCUMkPi7vLxDfcRe3-fCn_YtlbWDvPA3IbD_QUfiQB5EfYc8MdFh9kCcCuR_2IXupaH50ssTdnGmFjALg8iAiNg=s0-d-e1-ft#https://github.com/notifications/beacon/APC7TP7KXSBMMMEXHMV3IO3XSP4ZJA5CNFSM6AAAAAA23ZYOAOWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTCWZDNM.gif>Message
ID: ***@***.***>

-- 
Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by FariborzDaneshvar-NOAA** [comment]
### Florence 2018, `BEST` track run

**Comment by FariborzDaneshvar-NOAA** [comment]
### Florence 2018, `OFCL` track run

The following lines were updated in `pahm_control_florence.in`:

- bestTrackFileName = `/lustre/hurricanes/florence_2018_Fariborz_v4_15_ensembles/nhc_track/hurricane-track.dat`
- meshFileName = `/lustre/hurricanes/florence_2018_Fariborz_v3_39_ensembles/mesh/mesh_w_bdry.grd`
- meshFileName = `/lustre/hurricanes/florence_2018_Fariborz_v3_39_ensembles/mesh` 
- outFileName = `pahm_windout_florence_OFCL`
- begDateTime = `2018-08-30 12:00:00`
- endDateTime = `2018-09-12 18:00:00`

This run **failed** with the following message:
```
(perturbation) [Fariborz.Daneshvar@nhccolab2-3 PaHM]$ ./pahm pahm_control_florence.in
The contol file : pahm_control_florence.in was found and will be opened for reading.
Finished processing the input fields from the control file ...
ERROR :: ProcessAsymmetricVortexData: 23 isotachs were nonzero.
ERROR :: ProcessAsymmetricVortexData: 23 isotachs were nonzero.
ERROR :: ProcessAsymmetricVortexData: 23 isotachs were nonzero.
ERROR :: ProcessAsymmetricVortexData: 23 isotachs were nonzero.
ERROR :: GetGAHMFields: The GAHM asymmetric data structure has more than 4 iSotachs in cycle 54.
ERROR :: Terminate: PaHM Terminating.
```

**Comment by FariborzDaneshvar-NOAA** [comment]
### Comparison of `BEST` & `OFCL` track files created by the `ondemand-storm-workflow` runs:

Here are first few lines of two `nhc_track` files for comparison
Florence, 2018 - `BEST`:
```
AL, 06, 2018083006,   , BEST,   0, 128N,  169W,  20, 1008, LO,   0,    ,    0,    0,    0,    0, 1010,  150,  50,   0,   0,   L,   0,    ,   0,   0,     INVEST,,,,,,,,
AL, 06, 2018083012,   , BEST,   0, 128N,  179W,  25, 1007, LO,   0,    ,    0,    0,    0,    0, 1010,  150,  50,   0,   0,   L,   0,    , 270,   5,        SIX,,,,,,,,
AL, 06, 2018083018,   , BEST,   0, 128N,  190W,  25, 1007, LO,   0,    ,    0,    0,    0,    0, 1010,  150,  50,  35,   0,   L,   0,    , 270,   6,        SIX,,,,,,,,
AL, 06, 2018083100,   , BEST,   0, 131N,  202W,  30, 1006, LO,   0,    ,    0,    0,    0,    0, 1010,  150,  40,  40,   0,   L,   0,    , 284,   6,        SIX,,,,,,,,
AL, 06, 2018083106,   , BEST,   0, 134N,  214W,  30, 1006, LO,   0,    ,    0,    0,    0,    0, 1010,  150,  40,  40,   0,   L,   0,    , 284,   6,        SIX,,,,,,,,
AL, 06, 2018083112,   , BEST,   0, 136N,  226W,  30, 1006, LO,   0,    ,    0,    0,    0,    0, 1010,  150,  40,  40,   0,   L,   0,    , 280,   6,        SIX,,,,,,,,
AL, 06, 2018083118,   , BEST,   0, 138N,  238W,  30, 1006, TD,   0,    ,    0,    0,    0,    0, 1010,  150,  40,  40,   0,   L,   0,    , 280,   6,        SIX,,,,,,,,
AL, 06, 2018090100,   , BEST,   0, 140N,  249W,  30, 1006, TD,   0,    ,    0,    0,    0,    0, 1010,  150,  40,  40,   0,   L,   0,    , 281,   6,        SIX,,,,,,,,
AL, 06, 2018090106,   , BEST,   0, 143N,  261W,  35, 1005, TS,  34, NEQ,   30,   30,    0,   30, 1010,  150,  30,  45,   0,   L,   0,    , 285,   6,        SIX,,,,,,,,
AL, 06, 2018090112,   , BEST,   0, 148N,  272W,  35, 1004, TS,  34, NEQ,   30,   30,    0,   30, 1010,  150,  30,  45,   0,   L,   0,    , 295,   6,   FLORENCE,,,,,,,,
```

Florence, 2018 - `OFCL`:
```
AL, 06, 2018083012, 03, OFCL,   0, 128N,  179W,  25, 1007, LO,  34, NEQ,    0,    0,    0,    0, 1010,    0,  30,  35,   0,    ,   0, LAA,   0,   0,           ,,,,,,,,
AL, 06, 2018083018, 03, OFCL,   0, 128N,  190W,  25, 1007, LO,  34, NEQ,    0,    0,    0,    0, 1010,    0,  30,  35,   0,    ,   0, LAA, 270,   6,           ,,,,,,,,
AL, 06, 2018083100, 03, OFCL,   0, 131N,  202W,  30, 1007, LO,  34, NEQ,    0,    0,    0,    0, 1010,    0,  40,  40,   0,    ,   0, JLB, 284,   6,           ,,,,,,,,
AL, 06, 2018083106, 03, OFCL,   0, 134N,  210W,  30, 1006, LO,  34, NEQ,    0,    0,    0,    0, 1009,    0,  40,  40,   0,    ,   0, RJB, 291,   4,           ,,,,,,,,
AL, 06, 2018083112, 03, OFCL,   0, 135N,  221W,  30, 1006, LO,  34, NEQ,    0,    0,    0,    0, 1009,    0,  40,  40,   0,    ,   0, LAA, 275,   6,           ,,,,,,,,
AL, 06, 2018083118, 03, OFCL,   0, 138N,  240W,  30, 1004, TD,  34, NEQ,    0,    0,    0,    0, 1009,    0,  40,  40,   0,    ,   0, LAA, 279,  10,           ,,,,,,,,
AL, 06, 2018090100, 03, OFCL,   0, 140N,  249W,  30, 1004, TD,  34, NEQ,    0,    0,    0,    0, 1010,    0,  40,  40,   0,    ,   0, JLB, 283,   5,           ,,,,,,,,
AL, 06, 2018090106, 03, OFCL,   0, 143N,  261W,  35, 1003, TS,  34, NEQ,   30,   30,    0,   30, 1009,    0,  30,  45,   0,    ,   0, RJB, 285,   6,           ,,,,,,,,
AL, 06, 2018090112, 03, OFCL,   0, 146N,  273W,  35, 1003, TS,  34, NEQ,   30,   30,    0,   30, 1009,    0,  30,  45,   0,    ,   0, LAA, 285,   6,           ,,,,,,,,
AL, 06, 2018090118, 03, OFCL,   0, 154N,  283W,  40, 1002, TS,  34, NEQ,   40,   40,   20,   40, 1009,    0,  30,  50,   0,    ,   0, LAA, 310,   6,           ,,,,,,,,
```

**Comment by pvelissariou1** [comment]
This is because of the timestamps in the file I believe. I will check on
this on Monday. We will talk then.

Takis

On Saturday, July 29, 2023, Fariborz Daneshvar ***@***.***>
wrote:
> Comparison of BEST & OFCL track files created by the
ondemand-storm-workflow runs:
>
> Here are first few lines of two nhc_track files for comparison
> Florence, 2018 - BEST:
>
> AL, 06, 2018083006, , BEST, 0, 128N, 169W, 20, 1008, LO, 0, , 0, 0, 0, 0,
1010, 150, 50, 0, 0, L, 0, , 0, 0, INVEST,,,,,,,,
> AL, 06, 2018083012, , BEST, 0, 128N, 179W, 25, 1007, LO, 0, , 0, 0, 0, 0,
1010, 150, 50, 0, 0, L, 0, , 270, 5, SIX,,,,,,,,
> AL, 06, 2018083018, , BEST, 0, 128N, 190W, 25, 1007, LO, 0, , 0, 0, 0, 0,
1010, 150, 50, 35, 0, L, 0, , 270, 6, SIX,,,,,,,,
> AL, 06, 2018083100, , BEST, 0, 131N, 202W, 30, 1006, LO, 0, , 0, 0, 0, 0,
1010, 150, 40, 40, 0, L, 0, , 284, 6, SIX,,,,,,,,
> AL, 06, 2018083106, , BEST, 0, 134N, 214W, 30, 1006, LO, 0, , 0, 0, 0, 0,
1010, 150, 40, 40, 0, L, 0, , 284, 6, SIX,,,,,,,,
> AL, 06, 2018083112, , BEST, 0, 136N, 226W, 30, 1006, LO, 0, , 0, 0, 0, 0,
1010, 150, 40, 40, 0, L, 0, , 280, 6, SIX,,,,,,,,
> AL, 06, 2018083118, , BEST, 0, 138N, 238W, 30, 1006, TD, 0, , 0, 0, 0, 0,
1010, 150, 40, 40, 0, L, 0, , 280, 6, SIX,,,,,,,,
> AL, 06, 2018090100, , BEST, 0, 140N, 249W, 30, 1006, TD, 0, , 0, 0, 0, 0,
1010, 150, 40, 40, 0, L, 0, , 281, 6, SIX,,,,,,,,
> AL, 06, 2018090106, , BEST, 0, 143N, 261W, 35, 1005, TS, 34, NEQ, 30, 30,
0, 30, 1010, 150, 30, 45, 0, L, 0, , 285, 6, SIX,,,,,,,,
> AL, 06, 2018090112, , BEST, 0, 148N, 272W, 35, 1004, TS, 34, NEQ, 30, 30,
0, 30, 1010, 150, 30, 45, 0, L, 0, , 295, 6, FLORENCE,,,,,,,,
>
> Florence, 2018 - OFCL:
>
> AL, 06, 2018083012, 03, OFCL, 0, 128N, 179W, 25, 1007, LO, 34, NEQ, 0, 0,
0, 0, 1010, 0, 30, 35, 0, , 0, LAA, 0, 0, ,,,,,,,,
> AL, 06, 2018083018, 03, OFCL, 0, 128N, 190W, 25, 1007, LO, 34, NEQ, 0, 0,
0, 0, 1010, 0, 30, 35, 0, , 0, LAA, 270, 6, ,,,,,,,,
> AL, 06, 2018083100, 03, OFCL, 0, 131N, 202W, 30, 1007, LO, 34, NEQ, 0, 0,
0, 0, 1010, 0, 40, 40, 0, , 0, JLB, 284, 6, ,,,,,,,,
> AL, 06, 2018083106, 03, OFCL, 0, 134N, 210W, 30, 1006, LO, 34, NEQ, 0, 0,
0, 0, 1009, 0, 40, 40, 0, , 0, RJB, 291, 4, ,,,,,,,,
> AL, 06, 2018083112, 03, OFCL, 0, 135N, 221W, 30, 1006, LO, 34, NEQ, 0, 0,
0, 0, 1009, 0, 40, 40, 0, , 0, LAA, 275, 6, ,,,,,,,,
> AL, 06, 2018083118, 03, OFCL, 0, 138N, 240W, 30, 1004, TD, 34, NEQ, 0, 0,
0, 0, 1009, 0, 40, 40, 0, , 0, LAA, 279, 10, ,,,,,,,,
> AL, 06, 2018090100, 03, OFCL, 0, 140N, 249W, 30, 1004, TD, 34, NEQ, 0, 0,
0, 0, 1010, 0, 40, 40, 0, , 0, JLB, 283, 5, ,,,,,,,,
> AL, 06, 2018090106, 03, OFCL, 0, 143N, 261W, 35, 1003, TS, 34, NEQ, 30,
30, 0, 30, 1009, 0, 30, 45, 0, , 0, RJB, 285, 6, ,,,,,,,,
> AL, 06, 2018090112, 03, OFCL, 0, 146N, 273W, 35, 1003, TS, 34, NEQ, 30,
30, 0, 30, 1009, 0, 30, 45, 0, , 0, LAA, 285, 6, ,,,,,,,,
> AL, 06, 2018090118, 03, OFCL, 0, 154N, 283W, 40, 1002, TS, 34, NEQ, 40,
40, 20, 40, 1009, 0, 30, 50, 0, , 0, LAA, 310, 6, ,,,,,,,,
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci4.googleusercontent.com/proxy/mpK9jCIx-UdDfavHAUUESMSpgSaidYWn4_6IA_BzzdEGeQwZZZutRBZh-ZKIqmkFyFZpyI7Is_YttVh_ddcI3by4LWUWeWe3EF_Cnxu2fxysiQi4-EtfWyEuRKJ_xd1Scrf-6JW0S8D-C1syB1RJn9S86WnpPWKuNjFctFdU6yZNwtlKxfM0MJTYHidA-2TqumPmZYR9_UI1E6O1gii3HpDIrgIxIFzgIse-McW9GmoSB3Za1A=s0-d-e1-ft#https://github.com/notifications/beacon/APC7TPYAUNDZJKZX2MEPBG3XSVAWNA5CNFSM6AAAAAA23ZYOAOWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTCYCTY2.gif>Message
ID: ***@***.***>

-- 
Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by FariborzDaneshvar-NOAA** [comment]
@SorooshMani-NOAA there are three storm track files in the `nhc_track/` directory:
`hurricane-track.dat`, `hurricane-track.dat_adj`, and `hurricane-track.dat_asymvort`
 
which one do you want me to use for PaHM run?

**Comment by pvelissariou1** [comment]
@FariborzDaneshvar-NOAA You need to use hurricane-track.dat, the other two are generated from PaHM to be used by ADCIRC basically. hurricane-track.dat_adj is generated when using the Holland model in PaHM and hurricane-track.dat_asymvort is generated when using the GAHM model in PaHM.

**Comment by SorooshMani-NOAA** [comment]
@FariborzDaneshvar-NOAA I'm talking about the one in `setup/ensemble.dir/runs/track_files/original.22`. The `nhc_track/hurricane-track.dat` is the one before perturbation. The other two are generated after `PaHM` processes the input, so they are actually PaHM outputs. 

So this is where I would find the 3 files I talked about:
- Actual Best track: `<best-track-rundir>/nhc_track/hurricane-track.dat`
- Modified OFCL track: `<ofcl-track-rundir>/nhc_track/hurricane-track.dat`
- Fake Best track: `<ofcl-track-rundir>/setup/ensemble.dir/runs/track_files/original.22`

**Comment by FariborzDaneshvar-NOAA** [comment]
@pvelissariou1 and @SorooshMani-NOAA, I ran PaHM for these four track files:

1. Actual BEST track: `hurricane-track_BEST.dat` (path: `/lustre/hurricanes/florence_2018_Fariborz_BEST_10_v2/nhc_track/hurricane-track.dat`)
2. BEST track used for SCHISM run: `original_BEST.22` (path: `/lustre/hurricanes/florence_2018_Fariborz_BEST_10_v2/setup/ensemble.dir/track_files/original.22`)
3. Modified OFCL track: `hurricane-track_OFCL.dat` (path: `/lustre/hurricanes/florence_2018_Fariborz_OFCL_10_v2/nhc_track/hurricane-track.dat`)
4. Fake BEST track for SCHISM run:  `original_OFCL.22` (path: `/lustre/hurricanes/florence_2018_Fariborz_OFCL_10_v2/setup/ensemble.dir/track_files/original.22`)
 
Only the third run (for `hurricane-track_OFCL.dat`) failed with the following error message: 
```
The contol file : pahm_control_florence_OFCL.in was found and will be opened for reading.
Finished processing the input fields from the control file ...
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
libifcoremt.so.5   00002B2E0B6DB739  for__signal_handl     Unknown  Unknown
libpthread-2.17.s  00002B2E0EF75630  Unknown               Unknown  Unknown
libifcoremt.so.5   00002B2E0B74563B  for_len_trim          Unknown  Unknown
libifcoremt.so.5   00002B2E0B7455BF  for_trim              Unknown  Unknown
pahm               0000000000424CC9  Unknown               Unknown  Unknown
pahm               0000000000424847  Unknown               Unknown  Unknown
pahm               0000000000450215  Unknown               Unknown  Unknown
pahm               000000000048A18F  Unknown               Unknown  Unknown
pahm               000000000048A275  Unknown               Unknown  Unknown
pahm               0000000000402492  Unknown               Unknown  Unknown
libc-2.17.so       00002B2E0F1A4555  __libc_start_main     Unknown  Unknown
pahm               0000000000402399  Unknown               Unknown  Unknown
```

**Comment by FariborzDaneshvar-NOAA** [comment]
@pvelissariou1, for the failed run, I removed the last 20 lines of the `hurricane-track_OFCL.dat` with non-zero forecast hours (also copied below) and ran it again. This time it worked fine, Thanks!   

```
AL, 06, 2018091218, 03, OFCL,   3, 309N,  725W, 105,  949, HU,  34, NEQ,  170,  140,  100,  140, 1013,    0,  15, 130,  25,    ,   0, SRS, 314,   7,           ,,,,,,,,
AL, 06, 2018091218, 03, OFCL,   3, 309N,  725W, 105,  949, HU,  50, NEQ,  100,   80,   60,   80, 1013,    0,  15, 130,  25,    ,   0, SRS, 314,   7,           ,,,,,,,,
AL, 06, 2018091218, 03, OFCL,   3, 309N,  725W, 105,  949, HU,  64, NEQ,   60,   60,   40,   60, 1013,    0,  15, 130,  25,    ,   0, SRS, 314,   7,           ,,,,,,,,
AL, 06, 2018091218, 03, OFCL,  12, 321N,  741W, 110,  948, HU,  34, NEQ,  170,  140,  100,  140, 1013,    0,  15, 135,  25,    ,   0, SRS, 312,   6,           ,,,,,,,,
AL, 06, 2018091218, 03, OFCL,  12, 321N,  741W, 110,  948, HU,  50, NEQ,  100,   80,   60,   80, 1013,    0,  15, 135,  25,    ,   0, SRS, 312,   6,           ,,,,,,,,
AL, 06, 2018091218, 03, OFCL,  12, 321N,  741W, 110,  948, HU,  64, NEQ,   60,   60,   40,   60, 1013,    0,  15, 135,  25,    ,   0, SRS, 312,   6,           ,,,,,,,,
AL, 06, 2018091218, 03, OFCL,  24, 334N,  759W, 110,  948, HU,  34, NEQ,  170,  140,  100,  140, 1013,    0,  15, 135,  25,    ,   0, SRS, 311,   5,           ,,,,,,,,
AL, 06, 2018091218, 03, OFCL,  24, 334N,  759W, 110,  948, HU,  50, NEQ,  100,   80,   60,   80, 1013,    0,  15, 135,  25,    ,   0, SRS, 311,   5,           ,,,,,,,,
AL, 06, 2018091218, 03, OFCL,  24, 334N,  759W, 110,  948, HU,  64, NEQ,   60,   60,   40,   60, 1013,    0,  15, 135,  25,    ,   0, SRS, 311,   5,           ,,,,,,,,
AL, 06, 2018091218, 03, OFCL,  36, 339N,  771W, 105,  954, HU,  34, NEQ,  170,  140,  100,  140, 1013,    0,  15, 130,  25,    ,   0, SRS, 297,   3,           ,,,,,,,,
AL, 06, 2018091218, 03, OFCL,  36, 339N,  771W, 105,  954, HU,  50, NEQ,  100,   80,   60,   80, 1013,    0,  15, 130,  25,    ,   0, SRS, 297,   3,           ,,,,,,,,
AL, 06, 2018091218, 03, OFCL,  36, 339N,  771W, 105,  954, HU,  64, NEQ,   60,   60,   40,   60, 1013,    0,  15, 130,  25,    ,   0, SRS, 297,   3,           ,,,,,,,,
AL, 06, 2018091218, 03, OFCL,  48, 340N,  779W, 100,  959, HU,  34, NEQ,  170,  140,  100,  120, 1013,    0,  15, 120,  25,    ,   0, SRS, 279,   2,           ,,,,,,,,
AL, 06, 2018091218, 03, OFCL,  48, 340N,  779W, 100,  959, HU,  50, NEQ,  100,   80,   60,   60, 1013,    0,  15, 120,  25,    ,   0, SRS, 279,   2,           ,,,,,,,,
AL, 06, 2018091218, 03, OFCL,  48, 340N,  779W, 100,  959, HU,  64, NEQ,   60,   60,   40,   40, 1013,    0,  15, 120,  25,    ,   0, SRS, 279,   2,           ,,,,,,,,
AL, 06, 2018091218, 03, OFCL,  72, 336N,  792W,  70,  987, HU,  34, NEQ,  170,  140,   70,   70, 1013,    0,  15,  85,  25,    ,   0, SRS, 250,   1,           ,,,,,,,,
AL, 06, 2018091218, 03, OFCL,  72, 336N,  792W,  70,  987, HU,  50, NEQ,   80,   80,   40,   40, 1013,    0,  15,  85,  25,    ,   0, SRS, 250,   1,           ,,,,,,,,
AL, 06, 2018091218, 03, OFCL,  96, 340N,  817W,  30, 1008, TD,  34, NEQ,    0,    0,    0,    0, 1013,    0,  15,  40,  25,    ,   0, SRS, 282,   3,           ,,,,,,,,
AL, 06, 2018091218, 03, OFCL, 120, 356N,  834W,  20, 1011, LO,  34, NEQ,    0,    0,    0,    0, 1013,    0,  15,  30,  25,    ,   0, SRS, 319,   3,           ,,,,,,,,
AL, 06, 2018091218, 03, OFCL, 144, 391N,  820W,  15, 1012, EX,  34, NEQ,    0,    0,    0,    0, 1013,    0,  15,  20,  25,    ,   0, SRS,  17,   5,           ,,,,,,,,
```

**Comment by FariborzDaneshvar-NOAA** [comment]
Check this [ticket](https://github.com/oceanmodeling/ondemand-storm-workflow/issues/22) for the follow-up on PaHM-SCHISM runs of `BEST` and `OFCL` tracks
