### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by krober10nd** [noaa-ocs-modeling/PaHM#30]
Hi guys, could someone provide a simple example how to generate winds/pressures from Best Track data? Thanks

**Comment by pvelissariou1** [comment]
@krober10nd Hi Keith. Here is the link to the documentation of [PaHM](https://noaa-ocs-modeling.github.io/PaHM/).
1. After compilation of PaHM copy any of the sample files in PaHM/templates (for example pahm_control.tmpl) into pahm_control.in
2. Modify the pahm_control.in according to your needs
3. Run pahm as: pahm pahm_control.in. This will generate the output NetCDF file for the particular storm.
4. Important variables in pahm_control.in are
        - bestTrackFileName (location of best track filename)
        - meshFileType (always ADCIRC, this will allow to force the ADCIRC, SCHISM and possibly FVCOM models
        - meshFileName (the mesh file to use, see inputs/adcirc_mesh-shinnecock.dat)
        - unitTime (D, H, M, S)
        - outDT (output time interval). For hourly outputs, when unitTime=D use outDT=0.041666667
        - begDateTime and endDateTime, the begin/end simulation times, e.g: begDateTime=2018-08-30 12:00:00, endDateTime=2018-09-18 06:00:00 (if you use the DateTime variables comment out the begSimTime/endSimTime variables
        - modelType=1 or 10 the model to use (Holland/GAHM)

Compilation:
1. To compile pahm first run the build.sh script as: `build.sh --help` to see all the available options to the script
2. Run: build.sh [--platform linux] --compiler gnu to generate the `pahm` executable
NOTE: make sure that you use a recent version of CMake and that the NetCDF libraries are in your path. You might need to set the NETCDF_HOME environment variable before running the script.

I hope this answers your question.

**Comment by krober10nd** [comment]
Thank you very much. As an aside it could also be useful to export to a structured grid in the form of a netcdf file.

**Comment by pvelissariou1** [comment]
The structured and other meshes/grids are in the todo list. Thanks.
